### ISSUE TITLE
To-do items

### ISSUE THREAD

**Issue by turnerbaker1193** [turnerbaker1193/To-do-items#1]
## 介绍

在这篇文章中，我们将创建一个简单的前端项目，包括 HTML、CSS 和 JavaScript 文件。然后，我们将把这个项目上传到 GitHub，以便与大家分享。

## 项目概述

我们将创建一个简单的“待办事项”应用，它允许用户添加和删除待办事项。我们的项目结构将如下所示：

```
simple-todo-app/
├── index.html
├── styles.css
└── script.js
```

### 1. 创建 `index.html`

在 `simple-todo-app` 文件夹中，创建一个名为 `index.html` 的文件，并添加以下代码：

```html
<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>简单待办事项应用</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div class="container">
        <h1>待办事项</h1>
        <input type="text" id="todo-input" placeholder="添加一个新的待办事项">
        <button id="add-btn">添加</button>
        <ul id="todo-list"></ul>
    </div>
    <script src="script.js"></script>
</body>
</html>
```

### 2. 创建 `styles.css`

接下来，创建一个名为 `styles.css` 的文件，并添加以下样式：

```css
body {
    font-family: Arial, sans-serif;
    background-color: #f4f4f4;
    margin: 0;
    padding: 20px;
}

.container {
    max-width: 400px;
    margin: 0 auto;
    background: #fff;
    padding: 20px;
    box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
}

h1 {
    text-align: center;
}

#todo-input {
    width: calc(100% - 80px);
    padding: 10px;
    margin-right: 10px;
    border: 1px solid #ccc;
    border-radius: 4px;
}

#add-btn {
    padding: 10px;
    background: #28a745;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

#add-btn:hover {
    background: #218838;
}

ul {
    list-style-type: none;
    padding: 0;
}

li {
    display: flex;
    justify-content: space-between;
    padding: 10px;
    border-bottom: 1px solid #ccc;
}

.delete-btn {
    padding: 5px 10px;
    background: #dc3545;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
}

.delete-btn:hover {
    background: #c82333;
}
```

### 3. 创建 `script.js`

最后，创建一个名为 `script.js` 的文件，并添加以下代码：

```javascript
document.getElementById('add-btn').addEventListener('click', function() {
    const input = document.getElementById('todo-input');
    const todoText = input.value.trim();

    if (todoText) {
        const li = document.createElement('li');
        li.textContent = todoText;

        const deleteButton = document.createElement('button');
        deleteButton.textContent = '删除';
        deleteButton.className = 'delete-btn';

        deleteButton.addEventListener('click', function() {
            li.remove();
        });

        li.appendChild(deleteButton);
        document.getElementById('todo-list').appendChild(li);

        input.value = ''; // 清空输入框
    } else {
        alert('请先输入待办事项');
    }
});
```

## 第二步：在 GitHub 上创建新仓库

1. 登录到 [GitHub](https://github.com) 。
2. 点击右上角的 "+" 按钮，选择 "New repository"。
3. 输入仓库名称（例如 `simple-todo-app` ），并选择 "Public"。
4. 点击 "Create repository"。

## 第三步：上传项目文件

1. 在本地打开终端或命令提示符，进入到你的项目文件夹 `simple-todo-app`。

2. 初始化 Git 仓库并添加代码文件：

   ```bash
   git init
   git add .
   git commit -m "初始提交：添加待办事项应用"
   ```

3. 将你的本地仓库链接到 GitHub：

   ```bash
   git remote add origin https://github.com/你的用户名/simple-todo-app.git
   ```

4. 推送代码到 GitHub：

   ```bash
   git push -u origin master
   ```

## 第四步：分享你的项目

完成上传后，你的项目将显示在 GitHub 上，你可以分享链接给朋友或同事：

```
https://github.com/你的用户名/simple-todo-app
```

## 总结

我们创建了一个简单的待办事项应用并将其上传到 GitHub。你可以根据自己的需求扩展功能，或改变样式。希望你喜欢这个小项目，欢迎留言讨论！
